#!/bin/bash

# USAGE: ignore <note_name>
# where <note_name> is a relative path to a markdown file from the notes directory

IGNORED_FILE="$PROJECTS_DIR/blog/note-upload/ignored-files.txt"

# check if a note name was provided
if [ -z $1 ]; then
    echo "Usage: ignore <note_name>"
    exit 1
fi

# check if the note exists
ABS_PATH=$NOTES_DIR/$1
if [ ! -f $ABS_PATH ]; then
    echo "Note $1 does not exist"
    exit 1
fi

# make sure doesn't start with a slash
if [[ $1 == /* ]]; then
    echo "Note name should be a relative path from the notes directory"
    exit 1
fi

# check if the note is already ignored
if grep -qx $1 $IGNORED_FILE; then
    echo "Note $1 is already ignored"
    exit 1
fi

# add the note to the ignored files list
echo $1 >>$IGNORED_FILE
